services:
  weather-app:
    container_name: weather-app
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        APP: weather-app
    ports:
      - 3000:3000
    depends_on:
      - redis
      - postgres
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    command: npm run start-weather-app:dev

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        APP: scheduler
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    command: npm run start-scheduler:dev

  redis:
    image: redis:latest
    ports:
      - 6379:6379

  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      - .env
