FROM node:22-alpine AS base

# development stage
FROM base AS development 

ARG APP 
ARG NODE_ENV=development 
ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/src/app 
COPY package*.json ./ 
RUN npm install
COPY . . 

